title: Samson-Mac
description: hi :) im samson but you call me mac. im a 17 yr old trans guy living with ocd and i needed a place to put my thoughts :]
baseurl: "/samsbrain" 
url: "https://quinceypmorris.github.io/samson-mac" 
theme: minima
